### ISSUE TITLE
1.9.4-1.0.2 error in server console

### ISSUE THREAD

**Issue by kreezxil** [K-4U/ColorChat#5]
```
[09:32:53] [Server thread/INFO]: An unknown error occurred while attempting to perform this command
[09:32:53] [Server thread/WARN]: Couldn't process command: 'help'
java.lang.NullPointerException
        at k4unl.minecraft.colorchat.lib.User.isOpped(User.java:98) ~[User.class:?]
        at k4unl.minecraft.colorchat.commands.CommandColor.func_184882_a(CommandColor.java:114) ~[CommandColor.class:?]
        at net.minecraft.command.CommandHandler.func_71557_a(CommandHandler.java:197) ~[k.class:?]
        at com.matthewprenger.helpfixer.HelpFixer$1.func_184900_a(HelpFixer.java:39) ~[HelpFixer$1.class:1.3.14]
        at net.minecraft.command.CommandHelp.func_184881_a(SourceFile:73) ~[al.class:?]
        at net.minecraft.command.CommandHandler.func_175786_a(CommandHandler.java:103) [k.class:?]
        at net.minecraft.command.CommandHandler.func_71556_a(CommandHandler.java:82) [k.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:421) [lb.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:386) [lb.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:611) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:469) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
```

Was trying to see if the "spawn" command on my server had help. Not sure if this is related to your mod or not.

I'm using Forge 1.9.4 build 1963

**Comment by xenoflot** [comment]
Would you please publish a new release containing this fix?
